-- MySQL Script generated by MySQL Workbench
-- Thu Dec 28 18:48:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mundoCoxinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundoCoxinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundoCoxinha` DEFAULT CHARACTER SET utf8 ;
USE `mundoCoxinha` ;

-- -----------------------------------------------------
-- Table `mundoCoxinha`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`unidade` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoCoxinha`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `id_unidade` INT NOT NULL,
  PRIMARY KEY (`id_administrador`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_administrador_unidade1_idx` (`id_unidade` ASC),
  CONSTRAINT `fk_administrador_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `mundoCoxinha`.`unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoCoxinha`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `id_uf` VARCHAR(45) NULL,
  `referencia` VARCHAR(100) NULL,
  `id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_usuario_administrador1_idx` (`id_administrador` ASC),
  CONSTRAINT `fk_usuario_administrador1`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `mundoCoxinha`.`administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoCoxinha`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `qtd_estoque` INT ZEROFILL NOT NULL,
  `valor_venda` DECIMAL ZEROFILL NOT NULL,
  `id_administrador` INT NOT NULL,
  `valor_custo` DECIMAL ZEROFILL NOT NULL,
  `data_validade` DATE NOT NULL,
  `id_unidade` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_administrador_idx` (`id_administrador` ASC),
  INDEX `fk_produto_unidade1_idx` (`id_unidade` ASC),
  CONSTRAINT `fk_produto_administrador`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `mundoCoxinha`.`administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `mundoCoxinha`.`unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoCoxinha`.`status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`status_pedido` (
  `id_status_pedido` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoCoxinha`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoCoxinha`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_administrador` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `dh_pedido` DATETIME NOT NULL,
  `valor_total` DECIMAL UNSIGNED NOT NULL,
  `valor_entrega` DECIMAL NULL,
  `numero_pedido` INT NOT NULL,
  `id_status_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_administrador1_idx` (`id_administrador` ASC),
  INDEX `fk_pedido_usuario1_idx` (`id_cliente` ASC),
  INDEX `fk_pedido_produto1_idx` (`id_produto` ASC),
  INDEX `fk_pedido_status_pedido1_idx` (`id_status_pedido` ASC),
  CONSTRAINT `fk_pedido_administrador1`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `mundoCoxinha`.`administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mundoCoxinha`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mundoCoxinha`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_status_pedido1`
    FOREIGN KEY (`id_status_pedido`)
    REFERENCES `mundoCoxinha`.`status_pedido` (`id_status_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
